In [1]:
import numpy as np  # Standard convention using "np" alias


In [3]:
print(f"NumPy version: {np.__version__}")


NumPy version: 1.26.4


In [4]:
null_vector = np.zeros(10)  
print(null_vector) 


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
array = np.random.rand(100, 100)  
memory_size_bytes = array.nbytes
memory_size_megabytes = memory_size_bytes / 1024**2
print(f"Memory size of array: {memory_size_bytes} bytes, {memory_size_megabytes:.2f} MB")


Memory size of array: 80000 bytes, 0.08 MB


In [12]:
special_vector = np.zeros(10)
special_vector[4] = 1 
print(special_vector) 


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [13]:
vector = np.arange(10, 50)
print(vector)  


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [14]:
original_vector = np.array([1, 2, 3, 4, 5])
reversed_vector = original_vector[::-1]  
print(reversed_vector)  


[5 4 3 2 1]


In [15]:
matrix = np.arange(9).reshape(3, 3)  
print(matrix)  
        


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
array = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.where(array != 0)  
print(non_zero_indices)  


(array([0, 1, 4], dtype=int64),)


In [17]:
identity_matrix = np.eye(3)  
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
random_array = np.random.rand(3, 3, 3)  
print(random_array)  


[[[0.3565018  0.38722971 0.62653518]
  [0.40590306 0.54214634 0.26642921]
  [0.04234807 0.01460001 0.25718305]]

 [[0.53871557 0.09218422 0.88642444]
  [0.98141783 0.55700488 0.83086226]
  [0.9831725  0.77647234 0.68715266]]

 [[0.25616265 0.35740564 0.6515618 ]
  [0.53117039 0.69960454 0.40746743]
  [0.1510122  0.66267487 0.6349536 ]]]


In [19]:
random_array = np.random.rand(10, 10)
min_value = np.min(random_array)
max_value = np.max(random_array)
print(f"Minimum value: {min_value}, Maximum value: {max_value}")


Minimum value: 0.009778003578968408, Maximum value: 0.9969121675185041


In [20]:
random_vector = np.random.rand(30)
mean_value = np.mean(random_vector)
print(f"Mean value: {mean_value}")


Mean value: 0.5526784082655484


In [21]:
border_array = np.ones((7, 7))
border_array[1:-1, 1:-1] = 0  
print(border_array)  


[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
